# Generated by Django 5.1.6 on 2025-03-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
