# Generated by Django 5.1.6 on 2025-06-15 09:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=3, verbose_name="day of week")),
            ],
        ),
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
        migrations.RemoveField(
            model_name="habit",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="periodicity",
        ),
        migrations.AddField(
            model_name="habit",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed for the last time per day.",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно"), ("monthly", "Ежемесячно")],
                default="daily",
                help_text="Select how often a good habit should be performed.",
                max_length=20,
                null=True,
                verbose_name="frequency",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="time_needed",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Enter time needed to perform a habit in seconds. Not more than 2 minutes (120 seconds).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="time needed",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(help_text="Enter the action to perform.", max_length=200, verbose_name="action"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Select whether a habit is pleasant or not.",
                verbose_name="pleasant or not",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Select whether you want other users to see your habit.",
                verbose_name="public or not",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Enter the place where you'll perform your habit.", max_length=200, verbose_name="place"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a related pleasant habit (as a reward). For good habits only!",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="related habit",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Enter the reward for habit performance.",
                max_length=200,
                null=True,
                verbose_name="reward",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed. For good habits only!",
                null=True,
                verbose_name="time",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="days_of_week",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select specific days when a good habit should be performed.",
                to="habits.week",
                verbose_name="day(s) of week",
            ),
        ),
    ]
