# Generated by Django 5.1.6 on 2025-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_end_time_alter_habit_is_pleasant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed for the last time per day. Only for good habits that should be performed several times per day!",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Select whether a habit is pleasant or not. Only pleasant habits can serve as rewards for good habits.",
                verbose_name="pleasant or not",
            ),
        ),
    ]
