# Generated by Django 5.1.6 on 2025-05-27 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="days_of_week",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select specific days when a good habit should be performed.",
                to="habits.week",
                verbose_name="day(s) of week",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed for the last time per day. Only for good habits that should be performed several times per day!",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно"), ("monthly", "Ежемесячно")],
                default="daily",
                help_text="Select how often a good habit should be performed. NOTE! A good habit should be performed at least once a week.",
                max_length=20,
                null=True,
                verbose_name="frequency",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Select whether you want other users to see your habit.",
                verbose_name="public or not",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed. For good habits only!",
                null=True,
                verbose_name="time",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_needed",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Enter time needed to perform a habit in seconds. Not more than 2 minutes (120 seconds).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="time needed",
            ),
        ),
    ]
