# Generated by Django 5.1.6 on 2025-06-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_days_of_week_alter_habit_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
        migrations.RemoveField(
            model_name="habit",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="periodicity",
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(help_text="Enter the action to perform.", max_length=200, verbose_name="action"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed for the last time per day. Only for good habits that should be performed several times per day!",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Select whether a habit is pleasant or not. Only pleasant habits can serve as rewards for good habits.",
                verbose_name="pleasant or not",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Enter the place where you'll perform your habit.", max_length=200, verbose_name="place"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a related pleasant habit (as a reward). For good habits only!",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="related habit",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Enter the reward for habit performance.",
                max_length=200,
                null=True,
                verbose_name="reward",
            ),
        ),
    ]
